version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/web'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
      - 'web'

  - package-ecosystem: 'composer'
    directory: '/server'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
      - 'server'
