version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/web'
    schedule:
      interval: 'monthly'
    reviewers:
      - 'centerRyo'
    labels:
      - 'dependencies'
      - 'Frontend'

  - package-ecosystem: 'composer'
    directory: '/server'
    schedule:
      interval: 'monthly'
    reviewers:
      - 'centerRyo'
    labels:
      - 'dependencies'
      - 'Backend'
